name: Deploy Express App to EB

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests (optional)
        run: |
          # Add your test commands here
          # python -m pytest tests/
          echo "Skipping tests for now"

      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x '*.git*' 'node_modules'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          application_name: test-express
          environment_name: Test-express-env
          version_label: ${{ github.sha }}
          region: us-east-2
          deployment_package: deploy.zip
