name: Deploy React App to EB

on:
  push:
    paths:
      - "react/**"
  pull_request:
    paths:
      - "react/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build React+Vite app
        run: npm run build

      - name: Run tests (optional)
        run: |
          # Add your test commands here
          # python -m pytest tests/
          echo "Skipping tests for now"

      - name: Check files before zipping
        run: |
          echo "Files in express directory:"
          ls -la
          echo "Checking for Dockerfile:"
          cat Dockerfile || echo "No Dockerfile found"
          echo "Checking package.json:"
          cat package.json

      - name: Check files before zipping
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la
          echo "Checking dist:"
          ls -la dist

      - name: Prepare deployment package
        run: |
          zip -r ../deploy.zip . -x 'node_modules/*' '.git/*'
          cd ..
          ls -la deploy.zip

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: test-react
          environment_name: Test-react-env
          version_label: ${{ github.sha }}
          region: us-east-2
          deployment_package: deploy.zip # Zip is at root level now
          existing_bucket_name: client-build-folder
